In [18]:
str = input ( "enter your expression:")
op = ""
for i in str:
    if i in "+-*/":
        op=i
        str=str.replace (op, " ")
        l =[]
        for i in str.split(" "):
            l.append (float (i))
            

enter your expression: 78-89


In [16]:
str = input ( "enter your expression:")
print (eval(str)

enter your expression: 78-9.8


68.2


In [20]:
DIP= {'A':1, 'B':1,'C':2,'D':3,'E':2,'F':2,'G':3}

DOP={}
for i in DIP. values ():
    if i in DOP.keys ():
        DOP[i]=DOP[i]+1
    else: 
        DOP[i]=1

print (DOP)


{1: 2, 2: 3, 3: 2}


In [36]:
def prime(number):
    if number <= 1:
        return False  
    if number <= 3:
        return True  
    if number % 2 == 0 or number % 3 == 0:
        return False  
    
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6

    return True

if __name__ == "__main__":
    number = int(input("Enter a number to check if it is prime: "))
    if prime(number):
        print(f"{number} is a prime number.")
    else:
        print(f"{number} is not a prime number.")

Enter a number to check if it is prime:  56


56 is not a prime number.


In [8]:
l= list(map (str,input().split()))

print (l)

 1 2 3 4


['1', '2', '3', '4']


In [25]:
class a:
    def __init__(self):
        self.a=10
        self.b=20
        def fun1(self):
            print("this is a fun1 from class a")



class b(a):
    def __init__(self):
        self.a=100
        self.b=200
        def fun1(self):
            print("this is a fun1 from class b")

if __name__ == "__main__":
    obj  =a()

    
    print(obj.a)
    print(obj.b)
   
            
        

10
20


In [5]:
#calculate mean
import numpy as np
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [76, 95, 85],
    [90, 85, 92],
    [88, 76, 89]
])
mean_scores = np.mean(scores, axis=0)
print(mean_scores)

[86.2 86.8 87.8]


In [11]:
#find median 
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [76, 95, 85],
    [90, 85, 92],
    [88, 76, 89]
])
median_scores = np.median(scores, axis=0)
print( median_scores)


Median scores for each student: [88. 88. 89.]


In [12]:
# max & min
min_scores = np.min(scores, axis=0)
max_scores = np.max(scores, axis=0)
print( min_scores)
print( max_scores)


Minimum scores for each subject: [76 76 78]
Maximum scores for each subject: [92 95 95]


In [30]:
#highest total
highest_score=np.max(scores ,axis=1)
print(highest_score)

[90 95 95 92 89]


In [13]:
#shorting 
sorted_scores = np.sort(scores, axis=0)

print(sorted_scores)

[[76 76 78]
 [85 85 85]
 [88 88 89]
 [90 90 92]
 [92 95 95]]


In [14]:
# rephase 
reshaped_scores = scores.T
print(reshaped_scores)

[[85 92 76 90 88]
 [90 88 95 85 76]
 [78 95 85 92 89]]
