In [19]:
arr2 =np .array([1,2,3,4,5],dtype=np.int16)
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [20]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [21]:
o=np.ones(4)
o

array([1., 1., 1., 1.])

In [22]:
ar=np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ar=np.arange(0,10,9)
ar

array([0, 9])

In [26]:
ran=np.random.rand(6)
ran

array([0.28528909, 0.99292099, 0.94791537, 0.82732555, 0.21501178,
       0.29685358])

In [27]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [54]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
ar3=np.zeros([5,5])
ar3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
i=np.eye(6)
i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [50]:
r1=np.random.rand(1,2,)
r1

array([[0.20553767, 0.97292319]])

print(r1.size)

In [62]:
ar2=np.short(ar2,)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [60]:
ar2.sum()

np.int64(45)

In [66]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [70]:
np.divide(ar2,1)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [1]:
import numpy as np
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [76, 95, 85],
    [90, 85, 92],
    [88, 76, 89]
])
mean_scores = np.mean(scores, axis=0)
print("Mean scores for each subject:", mean_scores)

Mean scores for each subject: [86.2 86.8 87.8]
